<?php 
include 'dbcon.php';
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','raichur','hobli1','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','raichur','hobli1','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','raichur','hobli1','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','raichur','hobli1','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','raichur','hobli1','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','manvi','hobli1','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','manvi','hobli1','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','manvi','hobli1','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','manvi','hobli1','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','manvi','hobli1','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sindhnur','hobli1','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sindhnur','hobli1','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sindhnur','hobli1','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sindhnur','hobli1','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sindhnur','hobli1','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Devadurga','hobli1','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Devadurga','hobli1','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Devadurga','hobli1','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Devadurga','hobli1','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Devadurga','hobli1','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Lingsugur','hobli1','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Lingsugur','hobli1','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Lingsugur','hobli1','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Lingsugur','hobli1','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Lingsugur','hobli1','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sirwar','hobli1','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sirwar','hobli1','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sirwar','hobli1','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur','Sirwar','hobli1','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Raichur',' Sirwar','hobli1','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Bijapur','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Bijapur','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Bijapur','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Bijapuri,'hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Bijapur','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Basavan Bagevadi','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Basavan Bagevadi','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Basavan Bagevadi','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Basavan Bagevadi','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Basavan Bagevadi','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Indi','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Indi','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Indi','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Indi','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Indi','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Muddebihal','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Muddebihal','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Muddebihal','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Muddebihal','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Muddebihal','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Sindagi','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Sindagi','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Sindagi','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Sindagi','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Sindagi','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Talikota','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Talikota','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Talikota','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Talikota','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Talikota','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Chadchan','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Chadchan','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Chadchan','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Chadchan','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Chadchan','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Devar Hipparagi','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Devar Hipparagi','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Devar Hipparagi','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Devar Hipparagi','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Devar Hipparagi','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Kolhar','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','  Kolhar','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Kolhar','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Kolhar','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Kolhar','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Nidagundi','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Nidagundi','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Nidagundi','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Nidagundi','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Nidagundi','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Babaleshwar','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Babaleshwar','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Babaleshwar','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Babaleshwar','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Babaleshwar','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Tikota','hobli2','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Tikota','hobli2','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Tikota','hobli2','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur','Tikota','hobli2','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Bijapur',' Tikota','hobli2','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Tumkur','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Tumkur','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Tumkur','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Tumkur','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Tumkur','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Chiknayakanhalli','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Chiknayakanhalli','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Chiknayakanhalli','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Chiknayakanhalli','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Chiknayakanhalli','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Kunigal','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Kunigal','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Kunigal','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Kunigal','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Kunigal','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Madhugiri','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Madhugiri','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Madhugiri','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Madhugiri','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Madhugiri','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Sira','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Sira','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Sira','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Sira','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Sira','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Tiptur','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Tiptur','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Tiptur','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Tiptur','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Tiptur','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Gubbi','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Gubbi','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Gubbi','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Gubbir','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Gubbi','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Koratagere','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Koratagere','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Koratagere','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Koratagere','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Koratagere','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Pavagada','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Pavagada','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Pavagada','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Pavagada','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Pavagada','hobli3','village5')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Turuvekere','hobli3','village1')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Turuvekere','hobli3','village2')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur','Turuvekere','hobli3','village3')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Turuvekere','hobli3','village4')");
mysql_query("insert into list (district,taluk,hobli,village) values ('Tumkur',' Turuvekere','hobli3','village5')");




?>